# Generated by Django 5.0 on 2024-01-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="comlete",
            new_name="complete",
        ),
    ]
